version: "3.8"

services:
  app:
    container_name: 'registration-flow-app'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'

  postgres:
    container_name: postgres-keycloak
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    volumes:
      - ./pg-data/keycloak:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    container_name: keycloak-spring-security-2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "127.0.0.1:8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"

  postgresMain:
    container_name: postgres-main
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: main_db
    ports:
      - "127.0.0.1:5431:5432"
    restart: unless-stopped
    volumes:
      - ./pg-data/local:/var/lib/postgresql/data

#  prometheus:
#    image: prom/prometheus:v2.24.1
#    container_name: 'prometheus'
#    volumes:
#      - ./monitoring/prometheus/:/etc/prometheus/
#    ports:
#      - '9090:9090'
#
#  grafana:
#    image: grafana/grafana:5.4.3
#    container_name: 'grafana'
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
#    env_file:
#      - ./monitoring/grafana/config.monitoring
#    depends_on:
#      - prometheus
