version: "3.8"

services:
  app:
    container_name: 'registration-flow-app'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8081'
    depends_on:
      - postgresMain
    networks:
      - net

  postgres:
    container_name: postgres-keycloak
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
      # jdbc:postgresql://82.146.35.68:5432/keycloak_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./pg-data/keycloak:/var/lib/postgresql/data
    networks:
      - net

  keycloak:
    image: jboss/keycloak
    container_name: keycloak-spring-security-2
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
    ports:
      - "8484:8443"
    depends_on:
      - postgres
    volumes:
      - ./realm-export.json:/tmp/realm.json
    networks:
      - net

  postgresMain:
    container_name: postgres-main
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: main_db
    restart: unless-stopped
    volumes:
      - ./pg-data/local:/var/lib/postgresql/data
    networks:
      - net

networks:
  net:
    driver: bridge
